export interface MenuItem {
    id: number;
    nameEs: string;
    nameEn: string;
    description?: string;
    descriptionEs?: string;
    price: number;
    uncertainPrice?: boolean;
}

export interface MenuCategory {
    id: string;
    nameEs: string;
    nameEn: string;
    description?: string;
    items: MenuItem[];
}

export const menuCategories: MenuCategory[] = [
    {
        id: "entradas",
        nameEs: "Entradas",
        nameEn: "Appetizers",
        items: [
            {
                id: 1,
                nameEs: "Ceviche de Camarones",
                nameEn: "Shrimp Ceviche",
                description: "Shrimp marinated in lime juice and spices",
                descriptionEs: "Camarones marinados en jugo de limón y especias",
                price: 19.5,
            },
            {
                id: 2,
                nameEs: "Ceviche de Pescado",
                nameEn: "Fish Ceviche",
                description: "Fresh fish marinated in lime juice, served with lettuce, yam or potato",
                descriptionEs: "Pescado fresco marinado en jugo de limón, servido con lechuga, camote o papas",
                price: 16.95,
            },
            {
                id: 3,
                nameEs: "Ceviche Mixto",
                nameEn: "Mixed Ceviche",
                description: "Fish, clams, shrimp, squid & octopus in lime juice with lettuce, yam & corn nuts",
                descriptionEs: "Pescado, almejas, camarones, calamares y pulpo en jugo de limón con lechuga, camote y cancha",
                price: 19.5,
            },
            {
                id: 4,
                nameEs: "Ceviche de Mariscos",
                nameEn: "Seafood Ceviche",
                description: "Clams, squid & octopus in lime juice and spices with lettuce, yam & corn nuts",
                descriptionEs: "Almejas, calamares y pulpo en jugo de limón y especias con lechuga, camote y cancha",
                price: 18.5,
            },
            {
                id: 5,
                nameEs: "Papa a la Huancaína",
                nameEn: "Huancaína Style Potato",
                description: "Halved potatoes on lettuce with Peruvian cheese salsa",
                descriptionEs: "Papas en mitades sobre lechuga con salsa de queso peruano",
                price: 9.99,
            },
            {
                id: 6,
                nameEs: "Yuca a la Huancaína",
                nameEn: "Huancaína Style Cassava",
                description: "Halved cassava on lettuce with Peruvian cheese salsa",
                descriptionEs: "Yuca en mitades sobre lechuga con salsa de queso peruano",
                price: 9.99,
            },
            {
                id: 7,
                nameEs: "Tamales de Pollo o Puerco",
                nameEn: "Chicken or Pork Tamales",
                description: "Traditional Peruvian tamales",
                descriptionEs: "Tamales peruanos tradicionales",
                price: 8.99,
            },
            {
                id: 8,
                nameEs: "Papa Rellena",
                nameEn: "Stuffed Potato",
                description: "Potato stuffed with seasoned meat",
                descriptionEs: "Papa rellena de carne sazonada",
                price: 8.99,
            },
        ],
    },
    {
        id: "sopas",
        nameEs: "Sopas",
        nameEn: "Soups",
        items: [
            {
                id: 9,
                nameEs: "Chupe de Camarones",
                nameEn: "Shrimp Soup",
                description: "Rich Peruvian shrimp chowder",
                descriptionEs: "Chupe de camarones peruano",
                price: 9.5,
            },
            {
                id: 10,
                nameEs: "Sopa de Choros",
                nameEn: "Mussels Soup",
                description: "Traditional mussel soup",
                descriptionEs: "Sopa tradicional de choros",
                price: 6.25,
            },
            {
                id: 11,
                nameEs: "Aguadito",
                nameEn: "Cilantro Chicken Soup",
                description: "Traditional Peruvian cilantro chicken soup",
                descriptionEs: "Sopa tradicional peruana de pollo con cilantro",
                price: 7.95,
            },
        ],
    },
    {
        id: "especialidad",
        nameEs: "Especialidad de la Casa",
        nameEn: "House Specials — Rotisserie Chicken",
        description: "Served with your choice of two sides: rice, beans, French fries, or salad",
        items: [
            {
                id: 12,
                nameEs: "1/4 Pollo",
                nameEn: "Quarter Chicken",
                description: "Quarter rotisserie chicken (chicken only)",
                descriptionEs: "Un cuarto de pollo a la brasa (solo pollo)",
                price: 10.75,
                uncertainPrice: true,
            },
            {
                id: 13,
                nameEs: "1/2 Pollo",
                nameEn: "Half Chicken",
                description: "Half rotisserie chicken with 2 sides",
                descriptionEs: "Medio pollo a la brasa con 2 acompañamientos",
                price: 16.35,
            },
            {
                id: 14,
                nameEs: "1 Pollo Entero",
                nameEn: "Whole Chicken",
                description: "Whole rotisserie chicken with sides",
                descriptionEs: "Pollo entero a la brasa con acompañamientos",
                price: 30.0,
            },
            {
                id: 15,
                nameEs: "Pollo Entero Solo",
                nameEn: "Whole Chicken Only",
                description: "Whole rotisserie chicken without sides",
                descriptionEs: "Pollo entero a la brasa sin acompañamientos",
                price: 23.0,
            },
        ],
    },
    {
        id: "carnes",
        nameEs: "Carnes",
        nameEn: "Beef & Meat",
        items: [
            {
                id: 16,
                nameEs: "Seco de Cordero",
                nameEn: "Lamb Stew",
                description: "Lamb stew cooked in cilantro with yucca, rice & beans",
                descriptionEs: "Estofado de cordero cocinado en cilantro con yuca, arroz y frijoles",
                price: 14.5,
                uncertainPrice: true,
            },
            {
                id: 17,
                nameEs: "Tallarín Saltado de Carne",
                nameEn: "Beef Sautéed Noodle",
                description: "Lean beef sautéed with onions, tomatoes & spaghetti",
                descriptionEs: "Carne de res magra salteada con cebollas, tomates y tallarines",
                price: 15.95,
                uncertainPrice: true,
            },
            {
                id: 18,
                nameEs: "Lomo Saltado",
                nameEn: "Sautéed Loin",
                description: "Lean beef sautéed with onions & tomatoes, served with rice & fries",
                descriptionEs: "Carne de res magra salteada con cebollas y tomates, servido con arroz y papas fritas",
                price: 16.5,
            },
            {
                id: 19,
                nameEs: "Bistec a lo Pobre",
                nameEn: "Steak & Eggs",
                description: "Steak with fried eggs, plantains & potatoes, served with rice & beans",
                descriptionEs: "Bistec con huevos fritos, plátanos y papas, servido con arroz y frijoles",
                price: 19.5,
            },
            {
                id: 20,
                nameEs: "Cau Cau",
                nameEn: "Tripe Stew",
                description: "Beef tripe and diced potatoes served with rice",
                descriptionEs: "Mondongo y papas picadas servido con arroz",
                price: 11.95,
            },
            {
                id: 21,
                nameEs: "Cau Cau Montado",
                nameEn: "Tripe Stew with Eggs",
                description: "Beef tripe and diced potatoes with rice and two fried eggs",
                descriptionEs: "Mondongo y papas picadas con arroz y dos huevos fritos",
                price: 14.95,
            },
        ],
    },
    {
        id: "pollos",
        nameEs: "Pollos",
        nameEn: "Poultry Dishes",
        items: [
            {
                id: 22,
                nameEs: "Arroz Chaufa de Pollo",
                nameEn: "Chicken Fried Rice",
                description: "Peruvian-style chicken fried rice",
                descriptionEs: "Arroz chaufa de pollo al estilo peruano",
                price: 13.95,
                uncertainPrice: true,
            },
            {
                id: 23,
                nameEs: "Tallarín Saltado de Pollo",
                nameEn: "Chicken Sautéed Noodle",
                description: "Chicken sautéed with onions, tomatoes & spaghetti",
                descriptionEs: "Pollo salteado con cebollas, tomates y tallarines",
                price: 13.95,
                uncertainPrice: true,
            },
            {
                id: 24,
                nameEs: "Ají de Gallina",
                nameEn: "Creamy Chicken",
                description: "Shredded chicken in spicy nut sauce with rice & potatoes",
                descriptionEs: "Pollo desmenuzado en salsa de nueces picante con arroz y papas",
                price: 14.95,
            },
        ],
    },
    {
        id: "mariscos",
        nameEs: "Mariscos y Pescado",
        nameEn: "Seafood & Fish",
        items: [
            {
                id: 25,
                nameEs: "Arroz con Mariscos",
                nameEn: "Seafood Rice",
                description: "Rice with mixed seafood",
                descriptionEs: "Arroz con mariscos mixtos",
                price: 18.95,
                uncertainPrice: true,
            },
            {
                id: 26,
                nameEs: "Arroz Chaufa de Mariscos",
                nameEn: "Seafood Fried Rice",
                description: "Peruvian-style seafood fried rice",
                descriptionEs: "Arroz chaufa de mariscos al estilo peruano",
                price: 18.95,
                uncertainPrice: true,
            },
            {
                id: 27,
                nameEs: "Jalea de Pescado",
                nameEn: "Fried Fish Platter",
                description: "Fried fish pieces with cassava, topped with creole sauce",
                descriptionEs: "Trozos de pescado frito con yuca, cubiertos con salsa criolla",
                price: 17.95,
                uncertainPrice: true,
            },
            {
                id: 28,
                nameEs: "Jalea Para 2",
                nameEn: "Fried Seafood Platter for 2",
                description: "Fried fish & seafood with cassava, topped with creole sauce",
                descriptionEs: "Pescado y mariscos fritos con yuca, cubiertos con salsa criolla",
                price: 34.95,
                uncertainPrice: true,
            },
            {
                id: 29,
                nameEs: "Pescado a lo Macho",
                nameEn: "Fish Macho Style",
                description: "Fried fish covered in a rich seafood sauce",
                descriptionEs: "Pescado frito cubierto en salsa de mariscos",
                price: 19.95,
                uncertainPrice: true,
            },
            {
                id: 30,
                nameEs: "Pescado Frito",
                nameEn: "Fried Fish",
                description: "Fried fish served with rice and onion sauce",
                descriptionEs: "Pescado frito servido con arroz y salsa de cebolla",
                price: 16.95,
            },
        ],
    },
    {
        id: "acompanantes",
        nameEs: "Órdenes de Acompañante",
        nameEn: "Side Orders",
        items: [
            {
                id: 31,
                nameEs: "Yuca Frita",
                nameEn: "Fried Cassava",
                price: 8.75,
            },
            {
                id: 32,
                nameEs: "Arroz",
                nameEn: "Rice",
                price: 4.0,
                uncertainPrice: true,
            },
            {
                id: 33,
                nameEs: "Frijoles",
                nameEn: "Beans",
                price: 4.0,
                uncertainPrice: true,
            },
            {
                id: 34,
                nameEs: "Papas Fritas",
                nameEn: "French Fries",
                price: 5.0,
                uncertainPrice: true,
            },
            {
                id: 35,
                nameEs: "Ensalada",
                nameEn: "Salad",
                price: 5.0,
                uncertainPrice: true,
            },
            {
                id: 36,
                nameEs: "Plátanos Fritos",
                nameEn: "Fried Plantains",
                price: 5.0,
                uncertainPrice: true,
            },
        ],
    },
    {
        id: "bebidas",
        nameEs: "Bebidas",
        nameEn: "Beverages",
        items: [
            {
                id: 37,
                nameEs: "Chicha Morada",
                nameEn: "Purple Corn Drink",
                price: 4.0,
                uncertainPrice: true,
            },
            {
                id: 38,
                nameEs: "Inca Kola",
                nameEn: "Inca Kola",
                price: 3.0,
                uncertainPrice: true,
            },
            {
                id: 39,
                nameEs: "Sodas",
                nameEn: "Sodas",
                price: 2.5,
                uncertainPrice: true,
            },
            {
                id: 40,
                nameEs: "Agua",
                nameEn: "Water",
                price: 2.0,
                uncertainPrice: true,
            },
        ],
    },
    {
        id: "postres",
        nameEs: "Postres",
        nameEn: "Desserts",
        items: [
            {
                id: 41,
                nameEs: "Picarones",
                nameEn: "Peruvian Sweet Potato Donuts",
                description: "Traditional Peruvian sweet potato & pumpkin donuts drizzled with chancaca syrup",
                descriptionEs: "Donuts tradicionales peruanos de camote y calabaza bañados en miel de chancaca",
                price: 8.99,
            },
        ],
    },
];
