export interface MenuItem {
    id: number;
    nameEs: string;
    nameEn?: string;
    description?: string;
    descriptionEs?: string;
    price?: number;
    prices?: { size: string; price: number }[];
    uncertainPrice?: boolean;
}

export interface MenuCategory {
    id: string;
    nameEs: string;
    nameEn: string;
    description?: string;
    items: MenuItem[];
}

export const menuCategories: MenuCategory[] = [
    {
        id: "entradas",
        nameEs: "Entradas",
        nameEn: "Appetizers",
        items: [
            {
                id: 1,
                nameEs: "Ceviche de Camarones",
                nameEn: "Shrimp Ceviche",
                description: "Shrimp marinated in lime juice and spices",
                descriptionEs: "Camarones marinados en jugo de lim\u00f3n y especias",
                price: 16.99,
            },
            {
                id: 2,
                nameEs: "Ceviche de Pescado",
                nameEn: "Fish Ceviche",
                description: "Fresh fish marinated in lime juice. Served with lettuce, yam or potato",
                descriptionEs: "Pescado fresco marinado en jugo de lim\u00f3n, servido con lechuga, camote o papas",
                price: 14.99,
            },
            {
                id: 3,
                nameEs: "Ceviche Mixto",
                nameEn: "Mixed Ceviche",
                description: "Fish, clams, shrimp, squid, octopus marinated in lime juice. Served with lettuce yam or potato and corn nuts",
                descriptionEs: "Pescado, almejas, camarones, calamares y pulpo en jugo de lim\u00f3n con lechuga, camote y cancha",
                price: 16.99,
            },
            {
                id: 5,
                nameEs: "Papa a la Huanca\u00edna",
                nameEn: "Huanca\u00edna Style Potato",
                description: "Halved potatoes served on lettuce with delicious Peruvian cheese sauce",
                descriptionEs: "Papas en mitades sobre lechuga con salsa de queso peruano",
                price: 8.99,
            },
            {
                id: 20,
                nameEs: "Cau Cau",
                nameEn: "Tripe Stew",
                description: "Tripe and diced potatoes served with rice",
                descriptionEs: "Mondongo y papas picadas servido con arroz",
                price: 9.99,
            },
            {
                id: 21,
                nameEs: "Cau Cau Montado",
                nameEn: "Tripe Stew with Eggs",
                description: "Tripe and diced potatoes served with rice topped with two fried eggs",
                descriptionEs: "Mondongo y papas picadas con arroz y dos huevos fritos",
                price: 11.99,
            },
            {
                id: 7,
                nameEs: "Tamales de Pollo \u00f3 Puerco",
                nameEn: "Chicken or Pork Tamales",
                description: "Peruvian tamales with chicken or pork",
                descriptionEs: "Tamales peruanos tradicionales",
                price: 6.99,
            },
            {
                id: 8,
                nameEs: "Papa Rellena",
                description: "Stuffed potato with beef",
                descriptionEs: "Papa rellena de carne sazonada",
                price: 6.99,
            },
            {
                id: 6,
                nameEs: "Yuca a la Huanca\u00edna",
                nameEn: "Huanca\u00edna Style Cassava",
                description: "Halved yuca (cassava) served on lettuce with delicious Peruvian cheese sauce",
                descriptionEs: "Yuca en mitades sobre lechuga con salsa de queso peruano",
                price: 8.99,
            },
        ],
    },
    {
        id: "especialidad",
        nameEs: "Especialidad de la Casa",
        nameEn: "House Specials \u2014 Rotisserie Chicken",
        description: "Served with your choice of two sides: rice, beans, French fries, salad, or salsa criolla",
        items: [
            {
                id: 12,
                nameEs: "1/4 de Pollo",
                nameEn: "Quarter Chicken",
                descriptionEs: "Un cuarto de pollo a la brasa (solo pollo)",
                price: 10.5,
            },
            {
                id: 13,
                nameEs: "1/2 de Pollo",
                nameEn: "Half Chicken",
                descriptionEs: "Medio pollo a la brasa con 2 acompa\u00f1amientos",
                price: 14.5,
            },
            {
                id: 14,
                nameEs: "1 Pollo Entero",
                nameEn: "Whole Chicken",
                descriptionEs: "Pollo entero a la brasa con acompa\u00f1amientos",
                price: 26.0,
            },
            {
                id: 15,
                nameEs: "1 Pollo Solo",
                nameEn: "Whole Chicken Only",
                descriptionEs: "Pollo entero a la brasa sin acompa\u00f1amientos",
                price: 18.0,
            },
            {
                id: 100,
                nameEs: "1/2  Pollo Solo",
                price: 9.5,
            },
            {
                id: 101,
                nameEs: "1/4 Pollo Solo",
                nameEn: "Quarter Chicken Only",
                descriptionEs: "Un cuarto de pollo a la brasa sin acompa\u00f1amientos",
                price: 6.5,
            },
        ],
    },
    {
        id: "carnes",
        nameEs: "Carnes",
        nameEn: "Beef & Meat",
        items: [
            {
                id: 16,
                nameEs: "Seco de Cordero",
                description: "Lamb stew cooked in cilantro with yucca, rice and beans",
                descriptionEs: "Estofado de cordero cocinado en cilantro con yuca, arroz y frijoles",
                price: 15.99,
            },
            {
                id: 18,
                nameEs: "Lomo Saltado",
                nameEn: "Saut\u00e9ed Loin",
                description: "Lean beef saut\u00e9ed with onions and tomatoes. Served with rice and french fries",
                descriptionEs: "Carne de res magra salteada con cebollas y tomates, servido con arroz y papas fritas",
                price: 14.5,
            },
            {
                id: 17,
                nameEs: "Tallar\u00edn Saltado de Carne",
                nameEn: "Beef Saut\u00e9ed Noodle",
                description: "Lean beef saut\u00e9ed with onions, tomatoes and spaghetti",
                descriptionEs: "Carne de res magra salteada con cebollas, tomates y tallarines",
                price: 14.5,
            },
            {
                id: 102,
                nameEs: "Arroz Chaufa de Carne",
                description: "Beef fried rice",
                descriptionEs: "Arroz chaufa de carne de res al estilo peruano",
                price: 14.5,
            },
            {
                id: 103,
                nameEs: "Bistec a la Chorrillana",
                description: "A juicy fried steak saut\u00e9ed with onions and tomatoes. Served with rice",
                descriptionEs: "Bistec frito jugoso salteado con cebollas y tomates, servido con arroz",
                price: 15.99,
            },
            {
                id: 104,
                nameEs: "Lomo Saltado Montado",
                nameEn: "Saut\u00e9ed Loin with Eggs",
                description: "Lean beef saut\u00e9ed with onions and tomatoes served with rice and french fries topped with two eggs",
                descriptionEs: "Carne de res magra salteada con cebollas y tomates, servida con arroz, papas fritas y dos huevos fritos",
                price: 14.99,
            },
            {
                id: 105,
                nameEs: "Lomo Saltado Mixto",
                nameEn: "Mixed Saut\u00e9ed Loin",
                description: "Lean beef and chicken saut\u00e9ed with onions and tomatoes. Served with rice and french fries",
                descriptionEs: "Carne de res y pollo salteados con cebollas y tomates, servido con arroz y papas fritas",
                price: 14.99,
            },
            {
                id: 106,
                nameEs: "Bistec Frito",
                description: "Fried steak served with rice, sliced tomatoes and lettuce",
                descriptionEs: "Bistec frito servido con arroz, rodajas de tomate y lechuga",
                price: 14.99,
            },
            {
                id: 107,
                nameEs: "Bistec Apanado",
                nameEn: "Breaded Steak",
                description: "Breaded fried steak served with rice, sliced tomatoes and lettuce",
                descriptionEs: "Bistec apanado frito servido con arroz, rodajas de tomate y lechuga",
                price: 14.99,
            },
            {
                id: 19,
                nameEs: "Bistec a lo Pobre",
                nameEn: "Steak & Eggs",
                description: "Fried steak and fried plantain. Served with rice, fried egg and french fries",
                descriptionEs: "Bistec con huevos fritos, pl\u00e1tanos y papas, servido con arroz y frijoles",
                price: 15.99,
            },
            {
                id: 108,
                nameEs: "Tallar\u00edn Verde con Milanesa o Bistec",
                nameEn: "Green Spaghetti with Breaded Steak or Steak",
                description: "Breaded steak served on top of spaghetti with special basil sauce and parmesan cheese",
                descriptionEs: "Milanesa o bistec servido sobre espaguetis en salsa verde de espinaca y albahaca, con queso parmesano",
                price: 15.99,
            },
        ],
    },
    {
        id: "sopas",
        nameEs: "Sopas",
        nameEn: "Soups",
        items: [
            {
                id: 11,
                nameEs: "Aguadito",
                nameEn: "Cilantro Chicken Soup",
                description: "Chicken and vegetables in a cilantro rice broth",
                descriptionEs: "Sopa tradicional peruana de pollo con cilantro",
                prices: [
                    { size: "Small", price: 6.95 },
                    { size: "Large", price: 9.99 },
                ],
            },
            {
                id: 109,
                nameEs: "Menestr\u00f3n",
                nameEn: "Peruvian Minestrone Soup",
                description: "Beef, potatoes, pasta, corn and legumes in a spinach basil broth",
                descriptionEs: "Sopa abundante con carne, papas, pasta, choclo y legumbres en caldo de espinaca y albahaca",
                prices: [
                    { size: "Small", price: 9.0 },
                    { size: "Large", price: 12.0 },
                ],
            },
            {
                id: 110,
                nameEs: "Sopa a la Criolla",
                nameEn: "Criolla Soup",
                description: "Creole noodle soup with beef and egg in a milk base",
                descriptionEs: "Sopa criolla de fideos con carne de res y huevo en base de leche",
                price: 12.99,
            },
            {
                id: 111,
                nameEs: "Parihuela",
                nameEn: "Peruvian Seafood Soup",
                description: "Seafood soup served with fish, clams, shrimp, squid and octopus in a clam broth",
                descriptionEs: "Sopa concentrada de mariscos con pescado, almejas, camarones, calamares y pulpo en caldo de cangrejo y choros",
                price: 15.99,
            },
            {
                id: 10,
                nameEs: "Sopa de Choros",
                nameEn: "Mussels Soup",
                description: "Mussel soup",
                descriptionEs: "Sopa tradicional de choros",
                price: 12.5,
            },
            {
                id: 112,
                nameEs: "Sopa a la Minuta",
                nameEn: "Minuta Soup",
                description: "Beef soup with potatoes and spaghetti",
                descriptionEs: "Sopa de carne molida de res con papas, fideos cabello de \u00e1ngel y un toque de leche",
                price: 12.95,
            },
            {
                id: 9,
                nameEs: "Chupe de Camarones",
                description: "Fresh shrimp soup with eggs and rice in a milk base",
                descriptionEs: "Chupe de camarones peruano",
                price: 15.99,
            },
            {
                id: 113,
                nameEs: "Sustancia de Pollo",
                nameEn: "Chicken Noodle Soup",
                description: "Chicken soup with noodles, onions and tomatoes",
                descriptionEs: "Consom\u00e9 de pollo concentrado con fideos, cebollas y tomates",
                price: 12.95,
            },
        ],
    },
    {
        id: "pollos",
        nameEs: "Pollos",
        nameEn: "Poultry Dishes",
        items: [
            {
                id: 114,
                nameEs: "Saltado de Pollo",
                nameEn: "Saut\u00e9ed Chicken",
                description: "Lean chicken saut\u00e9ed with onions and tomatoes. Served with rice and french fries",
                descriptionEs: "Trozos de pollo salteados con cebollas y tomates, servidos con arroz y papas fritas",
                price: 14.5,
            },
            {
                id: 23,
                nameEs: "Tallar\u00edn Saltado de Pollo",
                nameEn: "Chicken Saut\u00e9ed Noodle",
                description: "Lean chicken saut\u00e9ed with onions and tomatoes on spaghetti",
                descriptionEs: "Pollo salteado con cebollas, tomates y tallarines",
                price: 14.5,
            },
            {
                id: 22,
                nameEs: "Arroz Chaufa de Pollo",
                description: "Chicken fried rice",
                descriptionEs: "Arroz chaufa de pollo al estilo peruano",
                price: 14.5,
            },
            {
                id: 24,
                nameEs: "Aji de Gallina",
                nameEn: "Creamy Chicken",
                description: "Shredded chicken in spicy walnut sauce. Served with rice and potatoes",
                descriptionEs: "Pollo desmenuzado en salsa de nueces picante con arroz y papas",
                price: 14.5,
            },
            {
                id: 115,
                nameEs: "Tallar\u00edn Saltado Mixto",
                nameEn: "Mixed Saut\u00e9ed Noodles",
                description: "Lean chicken and beef saut\u00e9ed with onions and tomatoes on spaghetti",
                descriptionEs: "Pollo y carne salteados con cebollas y tomates sobre tallarines",
                price: 15.99,
            },
        ],
    },
    {
        id: "mariscos",
        nameEs: "Mariscos y Pescado",
        nameEn: "Seafood & Fish",
        items: [
            {
                id: 116,
                nameEs: "Saltado de Mariscos",
                description: "Sauteed seafood shrimp, squid, octopus, onions and tomatoes. Served with rice and french fries",
                descriptionEs: "Mariscos mixtos (camarones, calamar, pulpo) salteados con cebollas y tomates, con arroz y papas fritas",
                price: 15.99,
            },
            {
                id: 117,
                nameEs: "Tallar\u00edn Saltado de Mariscos",
                nameEn: "Seafood Saut\u00e9ed Noodle",
                description: "Sauteed seafood shrimp, squid, octopus, onions and tomatoes. Served with spaghetti",
                descriptionEs: "Mariscos mixtos salteados con cebollas y tomates sobre tallarines",
                price: 15.99,
            },
            {
                id: 26,
                nameEs: "Arroz Chaufa de Mariscos",
                description: "Seafood fried rice",
                descriptionEs: "Arroz chaufa de mariscos al estilo peruano",
                price: 15.99,
            },
            {
                id: 118,
                nameEs: "Jalea Empanizada",
                nameEn: "Crispy Fried Seafood Platter",
                description: "Breaded fried pieces of fish, seafood and yucca (cassava)",
                descriptionEs: "Trozos de pescado y mariscos fritos con yuca, cubiertos con salsa criolla",
                price: 24.99,
            },
            {
                id: 119,
                nameEs: "Saltado de Pescado",
                nameEn: "Saut\u00e9ed Fish",
                description: "Fish strips saut\u00e9ed with onions and tomatoes. Served with rice",
                descriptionEs: "Trozos de pescado salteados con cebollas y tomates, servidos con arroz",
                price: 15.99,
            },
            {
                id: 120,
                nameEs: "Tallar\u00edn Saltado de Camarones",
                nameEn: "Shrimp Saut\u00e9ed Noodle",
                description: "Shrimp, onions and tomatoes stir fried with spaghetti",
                descriptionEs: "Camarones salteados con cebollas, tomates y tallarines",
                price: 16.99,
            },
            {
                id: 30,
                nameEs: "Pescado Frito",
                description: "Deep fried fish served with rice topped in onion sauce",
                descriptionEs: "Pescado frito servido con arroz y salsa de cebolla",
                price: 15.99,
            },
            {
                id: 29,
                nameEs: "Pescado a lo Macho",
                nameEn: "Fish Macho Style",
                description: "Fillet of fish fried smothered with seafood in a lightly spicy aji panca and wine sauce served with steamed rice",
                descriptionEs: "Pescado frito cubierto en salsa de mariscos",
                price: 16.99,
            },
            {
                id: 121,
                nameEs: "Sudado de Pescado",
                nameEn: "Steamed Fish Stew",
                description: "Steamed fish, simmered with tomatoes and onions with a touch of wine",
                descriptionEs: "Pescado al vapor cocinado a fuego lento con tomates, cebollas y un toque de vino blanco",
                price: 16.95,
            },
            {
                id: 28,
                nameEs: "Jalea (Good for 2)",
                nameEn: "Fried Seafood Platter for 2",
                description: "Pieces of fried fish, seafood and yucca (cassava) topped with salsa criolla",
                descriptionEs: "Pescado y mariscos fritos con yuca, cubiertos con salsa criolla",
                price: 24.99,
            },
            {
                id: 27,
                nameEs: "Jalea de Pescado",
                nameEn: "Fried Fish Platter",
                description: "Pieces of fried fish topped with salsa criolla. Served with rice",
                descriptionEs: "Trozos de pescado frito con yuca, cubiertos con salsa criolla",
                price: 15.99,
            },
            {
                id: 122,
                nameEs: "Pescado a la Chorillana",
                nameEn: "Fish Chorrillana Style",
                description: "Deep fried fish topped with onions and tomatoes. Served with rice",
                descriptionEs: "Pescado frito cubierto con cebollas y tomates salteados, servido con arroz",
                price: 15.99,
            },
            {
                id: 123,
                nameEs: "Saltado de Camarones",
                description: "Sauteed shrimp with onions and tomatoes. Served with rice and french fries",
                descriptionEs: "Camarones salteados con cebollas y tomates, servidos con arroz y papas fritas",
                price: 16.99,
            },
            {
                id: 124,
                nameEs: "Arroz Chaufa de Camarones",
                description: "Shrimp fried rice",
                descriptionEs: "Arroz chaufa de camarones al estilo peruano",
                price: 16.99,
            },
            {
                id: 125,
                nameEs: "Mojarra Frita",
                description: "Fried mojarra (Saturdays & Sundays only)",
                descriptionEs: "Mojarra entera frita servida con arroz, ensalada y salsa criolla (Solo S\u00e1bados y Domingos)",
                price: 12.99,
            },
        ],
    },
    {
        id: "acompanantes",
        nameEs: "\u00d3rdenes de Acompa\u00f1ante",
        nameEn: "Side Orders",
        items: [
            {
                id: 31,
                nameEs: "Yuca Frita",
                description: "Fried cassava",
                price: 6.99,
            },
            {
                id: 33,
                nameEs: "Frijoles",
                description: "Beans",
                price: 5.99,
            },
            {
                id: 32,
                nameEs: "Arroz",
                description: "Rice",
                price: 5.99,
            },
            {
                id: 126,
                nameEs: "Salsa Criolla",
                nameEn: "Creole Onion Salsa",
                description: "Chopped onions and tomatoes marinated in lime juice",
                descriptionEs: "Cebollas rojas, tomates y aj\u00ed picados marinados en jugo de lim\u00f3n y culantro",
                price: 5.99,
            },
            {
                id: 36,
                nameEs: "Pl\u00e1tano Frito",
                description: "Fried plantains",
                price: 6.0,
            },
            {
                id: 127,
                nameEs: "Avocado o Palta",
                nameEn: "Avocado",
                descriptionEs: "Palta o aguacate fresco rebanado",
                price: 6.5,
            },
            {
                id: 34,
                nameEs: "Papas Fritas",
                description: "French fries",
                price: 5.99,
            },
            {
                id: 35,
                nameEs: "Ensalada",
                description: "Salad",
                price: 5.99,
            },
            {
                id: 128,
                nameEs: "Canchita",
                nameEn: "Toasted Corn Nuts",
                description: "Roasted corn nuts",
                descriptionEs: "Ma\u00edz cancha tostado tradicional peruano",
                price: 6.5,
            },
            {
                id: 129,
                nameEs: "Choclo",
                nameEn: "Peruvian Giant Corn",
                description: "Peruvian corn",
                descriptionEs: "Choclo entero cocido de grano grande peruano",
                price: 6.5,
            },
            {
                id: 130,
                nameEs: "Aji (Red or Green Hot Sauce)",
                descriptionEs: "Nuestra salsa de aj\u00ed picante casera (Roja o Verde)",
                prices: [
                    { size: "2oz", price: 1.0 },
                    { size: "8oz", price: 5.5 },
                ],
            },
        ],
    },
    {
        id: "postres",
        nameEs: "Postres",
        nameEn: "Desserts",
        items: [
            {
                id: 41,
                nameEs: "Picarones",
                nameEn: "Peruvian Sweet Potato Donuts",
                description: "Peruvian donuts (Saturdays & Sundays only)",
                descriptionEs: "Donuts tradicionales peruanos de camote y calabaza ba\u00f1ados en miel de chancaca",
                price: 9.5,
            },
            {
                id: 131,
                nameEs: "Helado de Lucuma",
                nameEn: "L\u00facuma Ice Cream",
                description: "Peruvian ice cream",
                descriptionEs: "Helado peruano artesanal elaborado con pulpa de l\u00facuma",
                prices: [
                    { size: "S", price: 7.0 },
                    { size: "M", price: 12.0 },
                    { size: "L", price: 18.0 },
                ],
            },
            {
                id: 132,
                nameEs: "Leche Asada",
                description: "Custard",
                descriptionEs: "Postre cl\u00e1sico horneado a base de leche y huevos con una capa caramelizada",
                price: 3.99,
            },
            {
                id: 133,
                nameEs: "Alfajores",
                nameEn: "Peruvian Shortbread Cookies",
                description: "Peruvian cookies",
                descriptionEs: "Galletas de maicena suaves rellenas de dulce de leche (manjar blanco) y espolvoreadas con az\u00facar glass",
                price: 3.99,
            },
        ],
    },
    {
        id: "bebidas",
        nameEs: "Bebidas",
        nameEn: "Beverages",
        items: [
            {
                id: 37,
                nameEs: "Chicha Morada",
                nameEn: "Purple Corn Drink",
                price: 3.99,
            },
            {
                id: 38,
                nameEs: "Inca Kola (Can)",
                price: 2.99,
            },
            {
                id: 134,
                nameEs: "Inka Kola (2 Litros)",
                descriptionEs: "Botella de 2 litros de Inca Kola, la bebida nacional de Per\u00fa",
                price: 6.0,
            },
            {
                id: 135,
                nameEs: "T\u00e9",
                descriptionEs: "T\u00e9 caliente filtrado",
                price: 3.5,
            },
            {
                id: 136,
                nameEs: "Caf\u00e9",
                descriptionEs: "Caf\u00e9 caliente pasado",
                price: 3.5,
            },
            {
                id: 137,
                nameEs: "Maracuy\u00e1",
                nameEn: "Passion Fruit Drink",
                descriptionEs: "Refresco natural casero de maracuy\u00e1",
                price: 3.99,
            },
        ],
    },
];
